import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Archive, Bluetooth, Camera, Check, Download, History, Moon, Plus, Printer, RotateCcw, Save, Search, Settings as SettingsIcon, Share2, Sun, Upload, Weight, X } from 'lucide-react';

import { backupToJson, recordsToCsv, shareOrDownload } from './domain/export';

import { classifyScan, normalizeScan, validateSettings } from './domain/scan';
import { type AppState, type RecordEntry, type Settings, type Theme } from './domain/types';
import { pairPrinter, sendPrintJob } from './devices/printer';
import { pairScale, type WeightReading } from './devices/scale';
import { clearAll, loadState, normalizeImportedState, saveState } from './storage/store';
import { useModalDialog } from './components/useModalDialog';

type View = 'work'|'history'|'settings';
type Notice = {kind:'success'|'error'|'info';text:string};
const CameraScanner=lazy(async()=>({default:(await import('./components/CameraScanner')).CameraScanner}));
const newId=()=>crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
const errorText=(e:unknown)=>e instanceof Error?e.message:'Unexpected error.';

export default function App(){
  const initial=useMemo(()=>loadState(window.localStorage),[]); const [state,setState]=useState<AppState>(initial.state);
  const [location,setLocation]=useState('');const [item,setItem]=useState('');const [liveWeight,setLiveWeight]=useState(0);const [lockedWeight,setLockedWeight]=useState<number|null>(null);
  const [view,setView]=useState<View>('work');const [manual,setManual]=useState(false);const [camera,setCamera]=useState(false);const [notice,setNotice]=useState<Notice|null>(initial.migrated?{kind:'info',text:'Legacy data migrated safely.'}:null);
  const [storageError,setStorageError]=useState(initial.warnings[0]??'');const [busy,setBusy]=useState(false);const [duplicate,setDuplicate]=useState<RecordEntry|null>(null);const [query,setQuery]=useState('');const [historyTab,setHistoryTab]=useState<'records'|'prints'>('records');
  const persistenceEnabled=useRef(initial.safeToPersist);const printer=useRef<Awaited<ReturnType<typeof pairPrinter>>|null>(null);const scale=useRef<Awaited<ReturnType<typeof pairScale>>|null>(null);const canvas=useRef<HTMLCanvasElement>(null);const settingsFile=useRef<HTMLInputElement>(null);const backupFile=useRef<HTMLInputElement>(null);
  const [printerConnected,setPrinterConnected]=useState(false);const [scaleConnected,setScaleConnected]=useState(false);const [updateAction,setUpdateAction]=useState<((reloadPage?:boolean)=>Promise<void>)|null>(null);const [offlineReady,setOfflineReady]=useState(false);
  const duplicateDialog=useModalDialog(()=>setDuplicate(null),Boolean(duplicate));
  const ready=Boolean(location&&item&&lockedWeight!==null&&Number.isFinite(lockedWeight)&&lockedWeight>=0);
  useEffect(()=>{document.documentElement.dataset.theme=state.theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',state.theme==='dark'?'#1b222c':'#f4f1ea');},[state.theme]);
  useEffect(()=>{if(!persistenceEnabled.current)return;const result=saveState(window.localStorage,state);queueMicrotask(()=>setStorageError(result.ok?'':`Changes are in memory only: ${result.error}`));},[state]);
  useEffect(()=>{const update=(e:Event)=>setUpdateAction(()=>((e as CustomEvent).detail));const offline=()=>setOfflineReady(true);window.addEventListener('pwa-update',update);window.addEventListener('pwa-offline',offline);return()=>{window.removeEventListener('pwa-update',update);window.removeEventListener('pwa-offline',offline);};},[]);
  useEffect(()=>()=>{void scale.current?.disconnect();printer.current?.disconnect();},[]);
  const flash=(kind:Notice['kind'],text:string)=>setNotice({kind,text});
  const applyScan=useCallback((raw:string)=>{try{const scan=classifyScan(raw,state.settings);if(scan.kind==='location'){setLocation(scan.value);flash('success',`Location set: ${scan.value}`);}else if(scan.kind==='item'){setItem(scan.value);flash('success',`Item set: ${scan.value}`);}else if(scan.kind==='save'){document.getElementById('save-action')?.click();}else if(scan.kind==='print'){document.getElementById('print-action')?.click();}else flash('error',`Unrecognized scan: ${scan.value||'(empty)'}`);}catch(e){flash('error',`Scan rules failed: ${errorText(e)}`);}},[state.settings]);
  useEffect(()=>{let buffer='';let timer:number|undefined;const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(target.matches('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='Enter'){if(buffer){e.preventDefault();applyScan(buffer);buffer='';}}else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey){buffer+=e.key;clearTimeout(timer);timer=window.setTimeout(()=>buffer='',160);}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);clearTimeout(timer);};},[applyScan]);
  const setTheme=(theme:Theme)=>setState(s=>({...s,theme}));
  const resetEntry=()=>{setLocation('');setItem('');setLiveWeight(0);setLockedWeight(null);flash('info','Entry cleared.');};
  const makeRecord=():RecordEntry=>({id:newId(),timestamp:new Date().toISOString(),location:normalizeScan(location),item:normalizeScan(item),weight:lockedWeight!});
  const createRecord=(record:RecordEntry=duplicate??makeRecord())=>{setState(s=>({...s,records:[record,...s.records]}));setDuplicate(null);setLockedWeight(null);flash('success','Record saved.');};
  const updateRecord=()=>{const pending=duplicate??makeRecord();const existing=state.records.filter(r=>r.item===pending.item).sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp))[0];if(!existing)return createRecord(pending);setState(s=>({...s,records:s.records.map(r=>r.id===existing.id?{...r,location:pending.location,weight:pending.weight,timestamp:pending.timestamp}:r)}));setDuplicate(null);setLockedWeight(null);flash('success','Most recent matching item updated.');};
  const save=()=>{if(!ready||busy)return;const pending=makeRecord();if(state.records.some(r=>r.item===pending.item)){setDuplicate(pending);return;}createRecord(pending);};
  const bluetooth=(): unknown=>{if(!navigator.bluetooth)throw new Error('Web Bluetooth is unavailable. Use Chrome on Android over HTTPS.');return navigator.bluetooth;};
  const pairPrinterNow=async()=>{printer.current?.disconnect();const connection=await pairPrinter(bluetooth() as Parameters<typeof pairPrinter>[0]);connection.device.addEventListener('gattserverdisconnected',()=>{if(printer.current?.device===connection.device){printer.current=null;setPrinterConnected(false);flash('info','Printer disconnected.');}},{once:true});printer.current=connection;setPrinterConnected(true);flash('success','Printer paired for this session.');return connection.characteristic;};
  const connectPrinter=async()=>{if(busy)return;try{setBusy(true);if(printer.current){printer.current.disconnect();printer.current=null;setPrinterConnected(false);flash('info','Printer disconnected.');return;}return await pairPrinterNow();}catch(e){setPrinterConnected(false);throw new Error(`Printer pairing failed: ${errorText(e)}`,{cause:e});}finally{setBusy(false);}};
  const connectScale=async()=>{try{setBusy(true);if(scale.current){const connection=scale.current;scale.current=null;setScaleConnected(false);try{await connection.disconnect();flash('info','Scale disconnected.');}catch(e){flash('error',`Scale disconnected, but notification cleanup failed: ${errorText(e)}`);}return;}const connection=await pairScale(bluetooth() as Parameters<typeof pairScale>[0],(reading:WeightReading)=>setLiveWeight(reading.kilograms),error=>flash('error',`Scale reading ignored: ${error.message}`));connection.device.addEventListener('gattserverdisconnected',()=>{if(scale.current?.device===connection.device){scale.current=null;setScaleConnected(false);flash('info','Scale disconnected.');}},{once:true});scale.current=connection;setScaleConnected(true);flash('success','Scale paired. Readings are not auto-reconnected.');}catch(e){setScaleConnected(false);flash('error',`Scale pairing failed: ${errorText(e)}`);}finally{setBusy(false);}};
  const print=async(record?:RecordEntry)=>{if(busy)return;const data=record??(ready?makeRecord():null);if(!data){flash('error','Location, item and a locked weight are required.');return;}try{setBusy(true);const characteristic=printer.current?.characteristic??await pairPrinterNow();if(!canvas.current)throw new Error('Label canvas is unavailable.');const {canvasToRaster,renderLabel}=await import('./domain/label');const ctx=renderLabel(canvas.current,state.settings,data);await sendPrintJob(characteristic,canvasToRaster(canvas.current,ctx));const printed={...data,id:newId(),timestamp:new Date().toISOString()};if(record){setState(s=>({...s,printHistory:[printed,...s.printHistory]}));flash('success','Label reprinted and added to print history.');}else if(state.records.some(r=>r.item===data.item)){setState(s=>({...s,printHistory:[printed,...s.printHistory]}));setDuplicate(data);flash('info','Label printed. Choose how to store the duplicate record.');}else{setState(s=>({...s,records:[data,...s.records],printHistory:[printed,...s.printHistory]}));setLockedWeight(null);flash('success','Label printed and record saved.');}}catch(e){flash('error',errorText(e));}finally{setBusy(false);}};
  const shown=(historyTab==='records'?state.records:state.printHistory).filter(r=>`${r.item} ${r.location} ${r.weight}`.toLowerCase().includes(query.toLowerCase()));
  const remove=(entry:RecordEntry)=>{if(!confirm(`Delete ${entry.item} from ${historyTab==='records'?'records':'print history'}?`))return;setState(s=>({...s,[historyTab==='records'?'records':'printHistory']:(historyTab==='records'?s.records:s.printHistory).filter(r=>r.id!==entry.id)}));};
  const importFile=async(file:File|undefined,kind:'settings'|'backup')=>{if(!file||busy)return;try{const parsed:unknown=JSON.parse(await file.text());if(kind==='settings'){const candidate=((parsed as {settings?:unknown})?.settings??parsed) as Settings;const errors=validateSettings(candidate);if(Object.keys(errors).length)throw new Error(Object.values(errors)[0]);setState(s=>({...s,settings:candidate}));}else{const restored=normalizeImportedState((parsed as {state?:unknown})?.state??parsed);persistenceEnabled.current=true;setStorageError('');setState(restored);}flash('success',`${kind==='settings'?'Settings':'Backup'} imported.`);}catch(e){flash('error',`Import rejected: ${errorText(e)}`);}};
  return <div className="app-shell">
    <header className="topbar"><button className="brand" disabled={busy} onClick={()=>setView('work')} aria-label="Track and Tag work screen"><img src={`${import.meta.env.BASE_URL}icons/icon-96x96.png`} alt=""/><span><strong>Track&amp;Tag</strong><small>Warehouse station</small></span></button><nav aria-label="Primary"><button disabled={busy} className={view==='work'?'active':''} onClick={()=>setView('work')} title="Work"><Weight/><span>Work</span></button><button disabled={busy} className={view==='history'?'active':''} onClick={()=>setView('history')} title="History"><History/><span>History</span></button><button disabled={busy} className={view==='settings'?'active':''} onClick={()=>setView('settings')} title="Settings"><SettingsIcon/><span>Settings</span></button><button onClick={()=>setTheme(state.theme==='dark'?'light':'dark')} title={`Use ${state.theme==='dark'?'light':'dark'} theme`} aria-label={`Use ${state.theme==='dark'?'light':'dark'} theme`}>{state.theme==='dark'?<Sun/>:<Moon/>}</button></nav></header>
    {(storageError||notice||updateAction||offlineReady)&&<div className="notice-stack" aria-live="polite">{storageError&&<div className="notice error">{storageError}</div>}{notice&&<button className={`notice ${notice.kind}`} onClick={()=>setNotice(null)}>{notice.text}<X aria-hidden="true"/></button>}{updateAction&&<div className="notice info">Update ready. Finish your entry, then <button disabled={busy} onClick={()=>void updateAction(true)}>reload</button>.</div>}{offlineReady&&<button className="notice info" onClick={()=>setOfflineReady(false)}>App is ready offline.<X/></button>}</div>}
    <main>
      {view==='work'&&<><section className="station-head"><div><p className="eyebrow">Active handling unit</p><h1>{ready?'Ready to record':'Build an entry'}</h1></div><button className="secondary" onClick={()=>setManual(true)}><Plus/> Manual entry</button></section>
      {!navigator.bluetooth&&<div className="callout warning"><Bluetooth/>Bluetooth is not supported in this browser. Manual records still work; use Chrome on Android over HTTPS for devices.</div>}
      <div className="work-grid"><section className="card scan-card"><header><div><p className="eyebrow">01 · Identify</p><h2>Scan details</h2></div><button className="icon-button" onClick={()=>setCamera(true)} title="Scan QR or DataMatrix" aria-label="Open camera scanner"><Camera/></button></header><dl><div><dt>Location</dt><dd>{location||<span>Awaiting scan</span>}</dd></div><div><dt>Item ID</dt><dd>{item||<span>Awaiting scan</span>}</dd></div></dl><p className="hint">Wedge scanner: scan location or item, then Enter. Command labels are supported.</p></section>
      <section className="card weight-card"><header><div><p className="eyebrow">02 · Weigh</p><h2>Weight</h2></div><button className={`device ${scaleConnected?'connected':''}`} onClick={()=>void connectScale()} disabled={busy} title={scaleConnected?'Disconnect scale':'Pair BLE scale'}><span/>{scaleConnected?'Connected':'Pair scale'}</button></header><div className={`weight-value ${lockedWeight!==null?'locked':''}`}>{(lockedWeight??liveWeight).toFixed(state.settings.decimalPlaces)}<small>kg</small></div><button className={lockedWeight!==null?'secondary wide':'primary wide'} onClick={()=>setLockedWeight(lockedWeight!==null?null:liveWeight)}>{lockedWeight!==null?<><RotateCcw/>Unlock weight</>:<><Check/>Lock weight</>}</button></section></div>
      <section className={`readiness ${ready?'ready':''}`}><span className="readiness-icon">{ready?<Check/>:<Archive/>}</span><div><strong>{ready?'Entry ready':'Waiting for required fields'}</strong><p>{ready?`${location} · ${item} · ${lockedWeight?.toFixed(state.settings.decimalPlaces)} kg`:'Add location, item ID and lock the weight.'}</p></div></section>
      <div className="action-dock"><button id="print-action" className="secondary" disabled={!ready||busy} onClick={()=>void print()}><Printer/>{busy?'Working…':'Print label'}</button><button id="save-action" className="success" disabled={!ready||busy} onClick={save}><Save/>Save record</button></div><button className="text-button reset-entry" onClick={resetEntry}>Clear current entry</button><canvas ref={canvas} hidden width="96" height="240"/></>}
      {view==='history'&&<section className="page"><div className="page-head"><div><p className="eyebrow">Audit trail</p><h1>History</h1></div><button className="secondary" disabled={!state.records.length} onClick={()=>void shareOrDownload(recordsToCsv(state.records),'track-and-tag-records.csv','text/csv;charset=utf-8')}><Share2/>Export CSV</button></div><div className="tabs" role="tablist"><button role="tab" aria-selected={historyTab==='records'} onClick={()=>setHistoryTab('records')}>Records <b>{state.records.length}</b></button><button role="tab" aria-selected={historyTab==='prints'} onClick={()=>setHistoryTab('prints')}>Prints <b>{state.printHistory.length}</b></button></div><label className="search"><Search/><span className="sr-only">Search history</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item, location or weight"/></label>{shown.length?<div className="record-list">{shown.map(r=><article className="record" key={r.id}><div><strong>{r.item}</strong><span>{r.location} · {new Date(r.timestamp).toLocaleString()}</span></div><b>{r.weight.toFixed(state.settings.decimalPlaces)} kg</b><div className="record-actions"><button className="icon-button" onClick={()=>void print(r)} title="Reprint" aria-label={`Reprint ${r.item}`}><Printer/></button><button className="icon-button danger" onClick={()=>remove(r)} title="Delete" aria-label={`Delete ${r.item}`}><X/></button></div></article>)}</div>:<div className="empty"><History/><h2>No matching {historyTab}</h2><p>{query?'Try a broader search.':'Completed work will appear here.'}</p></div>}</section>}
      {view==='settings'&&<SettingsPage key={JSON.stringify(state.settings)} state={state} setState={setState} pairPrinter={async()=>{try{await connectPrinter();}catch(e){flash('error',errorText(e));}}} printerConnected={printerConnected} onExportSettings={()=>void shareOrDownload(JSON.stringify(state.settings,null,2),'track-and-tag-settings.json','application/json')} onExportBackup={()=>void shareOrDownload(backupToJson(state),'track-and-tag-backup.json','application/json')} settingsFile={settingsFile} backupFile={backupFile} importFile={importFile} onReset={()=>{const answer=prompt('Type RESET to permanently erase all local Track&Tag data.');if(answer==='RESET'){clearAll(localStorage);persistenceEnabled.current=true;setStorageError('');setState({...loadState(localStorage).state});resetEntry();flash('success','All local data reset.');}else if(answer!==null)flash('error','Reset cancelled: confirmation did not match.');}}/>}
    </main>
    {manual&&<ManualModal initial={{location,item,weight:lockedWeight??liveWeight}} settings={state.settings} onClose={()=>setManual(false)} onApply={v=>{setLocation(v.location);setItem(v.item);setLiveWeight(v.weight);setLockedWeight(v.weight);setManual(false);flash('success','Manual values applied and weight locked.');}}/>}
    {camera&&<Suspense fallback={<div className="modal-backdrop"><div className="modal">Loading camera…</div></div>}><CameraScanner onClose={()=>setCamera(false)} onResult={value=>{setCamera(false);applyScan(value);}}/></Suspense>}
    {duplicate&&<div className="modal-backdrop"><section ref={duplicateDialog} className="modal confirm" role="dialog" aria-modal="true" aria-labelledby="duplicate-title"><p className="eyebrow">Duplicate item</p><h2 id="duplicate-title">{duplicate.item} already exists</h2><p>Choose exactly how to store this reading.</p><div className="modal-actions"><button className="secondary" onClick={()=>setDuplicate(null)}>Cancel</button><button className="secondary" onClick={()=>createRecord()}>Save as new</button><button className="primary" onClick={updateRecord}>Update latest</button></div></section></div>}
  </div>;
}

function ManualModal({initial,settings,onClose,onApply}:{initial:{location:string;item:string;weight:number};settings:Settings;onClose:()=>void;onApply:(v:{location:string;item:string;weight:number})=>void}){
  const dialog=useModalDialog<HTMLFormElement>(onClose);const [values,setValues]=useState({location:initial.location,item:initial.item,weight:String(initial.weight)});const [errors,setErrors]=useState<Record<string,string>>({});const submit=(e:React.FormEvent)=>{e.preventDefault();const next:Record<string,string>={};let loc:RegExp,item:RegExp;try{loc=new RegExp(settings.locationRegex);}catch{next.location='Location rule is invalid in Settings.';loc=/.*/;}try{item=new RegExp(settings.itemRegex);}catch{next.item='Item rule is invalid in Settings.';item=/.*/;}if(!values.location.trim())next.location='Location is required.';else if(!loc.test(values.location.trim()))next.location='Location does not match the configured rule.';if(!values.item.trim())next.item='Item ID is required.';else if(!item.test(values.item.trim()))next.item='Item ID does not match the configured rule.';if(values.weight.trim()===''||!Number.isFinite(Number(values.weight))||Number(values.weight)<0)next.weight='Enter a valid non-negative number, including zero.';setErrors(next);if(!Object.keys(next).length)onApply({location:normalizeScan(values.location),item:normalizeScan(values.item),weight:Number(values.weight)});};
  return <div className="modal-backdrop"><form ref={dialog} className="modal" role="dialog" aria-modal="true" aria-labelledby="manual-title" onSubmit={submit} noValidate><header><div><p className="eyebrow">Keyboard entry</p><h2 id="manual-title">Manual entry</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X/></button></header><Field label="Location" error={errors.location}><input autoFocus value={values.location} onChange={e=>setValues(v=>({...v,location:e.target.value}))}/></Field><Field label="Item ID" error={errors.item}><input value={values.item} onChange={e=>setValues(v=>({...v,item:e.target.value}))}/></Field><Field label="Weight (kg)" error={errors.weight}><input type="number" inputMode="decimal" min="0" step="any" value={values.weight} onChange={e=>setValues(v=>({...v,weight:e.target.value}))}/></Field><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" type="submit">Apply &amp; lock</button></div></form></div>;
}
function Field({label,error,children}:{label:string;error:string|undefined;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}{error&&<small className="field-error">{error}</small>}</label>}

function SettingsPage({state,setState,pairPrinter,printerConnected,onExportSettings,onExportBackup,settingsFile,backupFile,importFile,onReset}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>;pairPrinter:()=>Promise<void>;printerConnected:boolean;onExportSettings:()=>void;onExportBackup:()=>void;settingsFile:React.RefObject<HTMLInputElement|null>;backupFile:React.RefObject<HTMLInputElement|null>;importFile:(f:File|undefined,k:'settings'|'backup')=>Promise<void>;onReset:()=>void}){
 const [draft,setDraft]=useState({...state.settings,template:JSON.stringify(state.settings.template,null,2)});const [errors,setErrors]=useState<Record<string,string>>({});const save=()=>{let template:unknown;try{template=JSON.parse(draft.template);}catch(e){setErrors({template:`Invalid JSON: ${errorText(e)}`});return;}const candidate={...draft,decimalPlaces:Number(draft.decimalPlaces),template} as Settings;const invalid=validateSettings(candidate);setErrors(invalid);if(!Object.keys(invalid).length)setState(s=>({...s,settings:candidate}));};
 return <section className="page settings-page"><div className="page-head"><div><p className="eyebrow">Station configuration</p><h1>Settings</h1></div><button className={`device ${printerConnected?'connected':''}`} onClick={()=>void pairPrinter()}><span/>{printerConnected?'Printer paired':'Pair printer'}</button></div><div className="settings-grid"><section className="card"><h2>Scan rules</h2><Field label="Decimal places" error={errors.decimalPlaces}><input type="number" min="0" max="6" value={draft.decimalPlaces} onChange={e=>setDraft(d=>({...d,decimalPlaces:Number(e.target.value)}))}/></Field>{(['locationRegex','itemRegex','printCommandRegex','saveCommandRegex'] as const).map(key=><Field key={key} label={{locationRegex:'Location regex',itemRegex:'Item regex',printCommandRegex:'Print command regex',saveCommandRegex:'Save command regex'}[key]} error={errors[key]}><input value={draft[key]} spellCheck="false" onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}/></Field>)}</section><section className="card"><h2>Label template</h2><p className="hint">96×240 px. Types: text, barcode, qrcode, datamatrix. Placeholders: {'{location}'}, {'{item}'}, {'{weight}'}.</p><Field label="Template JSON" error={errors.template}><textarea rows={16} value={draft.template} spellCheck="false" onChange={e=>setDraft(d=>({...d,template:e.target.value}))}/></Field></section></div><button className="primary save-settings" onClick={save}><Save/>Save validated settings</button><section className="card data-tools"><h2>Data portability</h2><div className="tool-grid"><button className="secondary" onClick={onExportSettings}><Share2/>Share/export settings</button><button className="secondary" onClick={()=>settingsFile.current?.click()}><Upload/>Import settings</button><button className="secondary" onClick={onExportBackup}><Download/>Full JSON backup</button><button className="secondary" onClick={()=>backupFile.current?.click()}><Upload/>Restore full backup</button></div><input hidden ref={settingsFile} type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0],'settings')}/><input hidden ref={backupFile} type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0],'backup')}/></section><section className="danger-zone"><h2>Reset local data</h2><p>Erases records, print history, settings and theme on this device.</p><button className="danger-button" onClick={onReset}>Reset everything</button></section></section>;
}
